name: Archive Simulator version of DSKit
on:
  push:
    paths:
      - 'DSKit/**'
      - 'DSKitFramework/**'
      - 'fastlane/**'
jobs:
  test:
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, 'archive')"
    steps:
      - uses: actions/checkout@v1
      - name: Build all frameworks, test, and archive
        run: fastlane prepareForDeliverySimulatorVersion
      - name: Upload report result
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Simulator version of DSKit
          path: DSKitFramework
